databases:
  - name: Smazigah
    databaseName: Smazigah
    user: Smazigah

services:
  - type: web
    name: Smazigah
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Smazigah.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Smazigah
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4